# Generated by Django 3.1.7 on 2021-04-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitrix24', '0002_auto_20200721_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitrixuser',
            name='extranet',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
